"""The exact matched synthetic generator for the current HPOP model.

Implements the registered factorization

    p(U, rho) . p(S, z | delta_B, pi, P) . p(X | S, z, h(U), vartheta)

with the reusable structures ``(U, H = h(U))`` generated independently of the
trace-specific ``(S, z)``; the two interact only when the observations ``X`` are
generated. Per trace the generation order is fixed:

    1. take the fixed design trace length ``J_n``;
    2. ``S_n ~ p(S | J_n, delta_B)`` by the exact DP sampler in
       ``matched_segmentation_prior`` (normalized over widths in
       ``[MIN_BLOCK_WIDTH, MAX_BLOCK_WIDTH]``);
    3. ``z_n1 ~ Categorical(pi)``; ``z_nl ~ Categorical(P[z_{n,l-1}, :])`` with a
       structurally zero diagonal (``transitions.allowed_next``);
    4. each block is generated by the PRODUCTION recurrent execution model
       ``recurrent_rfs.sample_recurrent_rfs_sequence`` — the same
       ``recurrent_step_probabilities`` / ``recurrent_validity_update`` the
       likelihood replays — from ``q_0 = 0``, for exactly the sampled width;
    5. roles map to CPA labels through the injective ``ell_k`` (identity in the
       current registered model, where the observation alphabet IS the role set).

No recurrent state crosses a block boundary: every block draws from its own
dedicated RNG stream (``SeedSequence(master, spawn_key=...)``), so a block's
generated distribution provably cannot depend on any other block.

This module deliberately does NOT contain, call, or reuse the earlier Stage 6E2
corpus generator's block-count mechanism (a uniform draw of the number of blocks
followed by iid widths). The number of blocks here is never sampled; it is
determined by the exact segmentation draw. A source-level regression test
enforces this.
"""

from __future__ import annotations

import hashlib
import json
import math
from dataclasses import dataclass, field

import numpy as np

from hpop.mcmc_original.latent_poset import precedence_from_u
from hpop.mcmc_original.matched_segmentation_prior import (
    ends_of_widths, sample_segmentation_widths, width_sampling_tables,
)
from hpop.mcmc_original.recurrent_rfs import (
    RecurrentRFSParameters, sample_recurrent_rfs_sequence,
)
from hpop.mcmc_original.recurrent_scalar_posterior import PRIORS, TRUE_VALUES
from hpop.mcmc_original.sampler_u import sigma_rho_matrix
from hpop.mcmc_original.stage6c_frozen import RHO_LOWER, RHO_UPPER
from hpop.mcmc_original.stage6e_frozen import (
    DELTA_B, ETA_INITIAL, ETA_TRANSITION, LATENT_DIM, MAX_BLOCK_WIDTH,
    MIN_BLOCK_WIDTH, N_ROLES, N_SKILLS,
)
from hpop.mcmc_original.targets import log_boundary_prior, log_path_prior
from hpop.mcmc_original.transitions import allowed_next

__all__ = [
    "GENERATOR_VERSION", "MatchedTruth", "MatchedTrace", "MatchedCorpus",
    "supplied_truth", "sample_prior_truth", "validate_truth",
    "sample_initial_skill", "sample_next_skill", "block_rng", "component_rng",
    "generate_trace", "generate_corpus",
    "generator_complete_data_log_prob", "inference_complete_data_log_prob",
    "canonical_json", "sha256_hex", "truth_to_jsonable", "trace_to_jsonable",
    "corpus_to_jsonable", "corpus_hash", "trace_from_jsonable",
]

GENERATOR_VERSION = "1.0.0"

# RNG component codes inside one trace's spawn_key namespace.
_COMPONENT_SEGMENTATION = 0
_COMPONENT_LABELS = 1
_COMPONENT_BLOCK_BASE = 2
_SPLIT_CODES = {"train": 0, "heldout": 1}


# ===================================================================== truth objects
@dataclass(frozen=True)
class MatchedTruth:
    """Everything the generator conditions on. Frozen before observations exist."""

    u_by_skill: np.ndarray            # (K, m, d)
    pi: np.ndarray                    # (K,)
    transition: np.ndarray            # (K, K), zero diagonal
    beta: float
    omega: float
    lambda_rep: float
    lambda_back: float
    epsilon: float
    delta_b: float
    min_width: int
    max_width: int
    role_maps: tuple                  # ell_k: K tuples of m CPA labels, injective
    rho: float | None = None          # recorded when the truth was drawn from the prior
    mode: str = "supplied"

    def __post_init__(self) -> None:
        object.__setattr__(self, "u_by_skill",
                           np.array(self.u_by_skill, dtype=float, copy=True))
        object.__setattr__(self, "pi", np.array(self.pi, dtype=float, copy=True))
        object.__setattr__(self, "transition",
                           np.array(self.transition, dtype=float, copy=True))
        object.__setattr__(self, "role_maps",
                           tuple(tuple(int(v) for v in row) for row in self.role_maps))

    @property
    def n_skills(self) -> int:
        return int(self.u_by_skill.shape[0])

    @property
    def n_roles(self) -> int:
        return int(self.u_by_skill.shape[1])

    @property
    def latent_dim(self) -> int:
        return int(self.u_by_skill.shape[2])

    @property
    def scalars(self) -> dict:
        return {"beta": float(self.beta), "omega": float(self.omega),
                "lambda_rep": float(self.lambda_rep),
                "lambda_back": float(self.lambda_back)}

    def rfs_parameters(self) -> RecurrentRFSParameters:
        return RecurrentRFSParameters(
            beta=self.beta, epsilon=self.epsilon, shared_omega=self.omega,
            lambda_rep=self.lambda_rep, lambda_back=self.lambda_back)

    def precedence(self, skill: int) -> np.ndarray:
        return precedence_from_u(self.u_by_skill[int(skill)])

    def role_maps_are_identity(self) -> bool:
        return all(row == tuple(range(self.n_roles)) for row in self.role_maps)


def supplied_truth() -> MatchedTruth:
    """The pre-registered supplied truth: the Stage 6E2 registered configuration.

    The VALUES below are the Stage 6E2 registered truth (three distinct
    nondegenerate induced orders over m = 5 roles, d = 2), restated here rather
    than imported so this module carries no dependency on the old corpus
    generator. A parity test asserts the restatement equals the registered
    original, value for value.
    """
    u_by_skill = np.array([
        # skill 0: 0 > 2 > 3 > 4 (a chain), role 1 incomparable with everything
        [[4.0, 4.0], [0.0, 5.0], [3.0, 3.0], [2.0, 2.0], [1.0, 1.0]],
        # skill 1: 1 > 2 > 4 > 0 (a chain on different roles), role 3 incomparable
        [[1.0, 1.0], [4.0, 4.0], [3.0, 3.0], [0.0, 5.0], [2.0, 2.0]],
        # skill 2: a fan -- 4 dominates everything, 2 > 3, roles 0 and 1 otherwise free
        [[3.0, 0.0], [0.0, 3.0], [2.0, 2.0], [1.0, 1.0], [4.0, 4.0]],
    ], dtype=float)
    return MatchedTruth(
        u_by_skill=u_by_skill,
        pi=np.array([0.50, 0.30, 0.20]),
        transition=np.array([[0.00, 0.65, 0.35],
                             [0.30, 0.00, 0.70],
                             [0.75, 0.25, 0.00]]),
        beta=1.5, omega=math.log(0.85 / 0.15), lambda_rep=0.8, lambda_back=0.25,
        epsilon=0.02, delta_b=DELTA_B,
        min_width=MIN_BLOCK_WIDTH, max_width=MAX_BLOCK_WIDTH,
        role_maps=tuple(tuple(range(N_ROLES)) for _ in range(N_SKILLS)),
        rho=None, mode="supplied")


def sample_prior_truth(rng: np.random.Generator, n_skills: int = N_SKILLS,
                       n_roles: int = N_ROLES, latent_dim: int = LATENT_DIM,
                       delta_b: float = DELTA_B, epsilon: float = 0.02,
                       min_width: int = MIN_BLOCK_WIDTH,
                       max_width: int = MAX_BLOCK_WIDTH,
                       scalars: dict | None = None) -> MatchedTruth:
    """Prior-draw mode: ``rho`` and every ``U_k`` from the registered priors.

    ``rho ~ Beta(1, 1)`` truncated to ``(RHO_LOWER, RHO_UPPER)`` — with the
    registered ``fac = 1`` that is Uniform(0, 0.995) — then rows of each ``U_k``
    iid ``N(0, Sigma_rho)``; ``pi ~ Dirichlet(eta_initial * 1)`` and each row of
    ``P`` ~ Dirichlet(eta_transition) over ``allowed_next`` (zero diagonal).
    Scalars default to the registered true values.
    """
    rho = float(rng.uniform(RHO_LOWER, RHO_UPPER))
    sigma = sigma_rho_matrix(int(latent_dim), rho)
    chol = np.linalg.cholesky(sigma)
    u = np.array([
        [chol @ rng.standard_normal(int(latent_dim)) for _ in range(int(n_roles))]
        for _ in range(int(n_skills))], dtype=float)
    pi = rng.dirichlet(np.full(int(n_skills), float(ETA_INITIAL)))
    transition = np.zeros((int(n_skills), int(n_skills)))
    for h in range(int(n_skills)):
        allowed = allowed_next(h, int(n_skills))
        draw = rng.dirichlet(np.full(len(allowed), float(ETA_TRANSITION)))
        for k, value in zip(allowed, draw):
            transition[h, k] = value
    scalars = dict(TRUE_VALUES) if scalars is None else dict(scalars)
    return MatchedTruth(
        u_by_skill=u, pi=pi, transition=transition,
        beta=scalars["beta"], omega=scalars["omega"],
        lambda_rep=scalars["lambda_rep"], lambda_back=scalars["lambda_back"],
        epsilon=float(epsilon), delta_b=float(delta_b),
        min_width=int(min_width), max_width=int(max_width),
        role_maps=tuple(tuple(range(int(n_roles))) for _ in range(int(n_skills))),
        rho=rho, mode="prior_draw")


def _assert_strict_partial_order(closure: np.ndarray, skill: int) -> None:
    p = np.asarray(closure)
    if bool(np.any(np.diag(p))):
        raise AssertionError(f"skill {skill}: induced order is not irreflexive")
    if bool(np.any(p & p.T)):
        raise AssertionError(f"skill {skill}: induced order is not asymmetric (cycle)")
    if bool(np.any((p.astype(int) @ p.astype(int) > 0) & ~p)):
        raise AssertionError(f"skill {skill}: induced order is not transitively closed")


def validate_truth(truth: MatchedTruth) -> dict:
    """Registered-support validation of a truth configuration; raises on failure."""
    K, m, d = truth.u_by_skill.shape
    if K < 2:
        raise AssertionError("zero-diagonal transitions need at least 2 skills")
    for k in range(K):
        _assert_strict_partial_order(truth.precedence(k), k)
    pi = truth.pi
    if pi.shape != (K,) or np.any(pi < 0) or not math.isclose(
            float(pi.sum()), 1.0, abs_tol=1e-12):
        raise AssertionError(f"pi must be a length-{K} distribution, got {pi}")
    P = truth.transition
    if P.shape != (K, K) or np.any(P < 0):
        raise AssertionError(f"P must be a nonnegative ({K},{K}) matrix")
    if np.any(np.diag(P) != 0.0):
        raise AssertionError(f"P must have an exactly zero diagonal, got {np.diag(P)}")
    for h in range(K):
        row_sum = float(P[h].sum())
        if not math.isclose(row_sum, 1.0, abs_tol=1e-12):
            raise AssertionError(f"row {h} of P sums to {row_sum}, not 1")
    truth.rfs_parameters()          # raises if any scalar leaves its support
    for name in ("beta", "lambda_rep", "lambda_back"):
        if PRIORS[name]["support"] == "(0, inf)" and truth.scalars[name] <= 0:
            raise AssertionError(f"{name} must be positive")
    if not (0.0 < truth.delta_b < 1.0):
        raise AssertionError(f"delta_b must be in (0, 1), got {truth.delta_b}")
    if not (1 <= truth.min_width <= truth.max_width):
        raise AssertionError(f"illegal width support [{truth.min_width}, "
                             f"{truth.max_width}]")
    if truth.rho is not None and not (RHO_LOWER < truth.rho < RHO_UPPER):
        raise AssertionError(f"rho={truth.rho} outside ({RHO_LOWER}, {RHO_UPPER})")
    for k, row in enumerate(truth.role_maps):
        if len(row) != m or len(set(row)) != m:
            raise AssertionError(f"role map ell_{k} = {row} is not injective over "
                                 f"{m} roles")
    return {"n_skills": int(K), "n_roles": int(m), "latent_dim": int(d),
            "orders_are_strict_partial_orders": True,
            "pi_sums_to_one": True, "transition_rows_normalized": True,
            "transition_diagonal_exactly_zero": True,
            "scalars_in_support": True, "role_maps_injective": True}


# ================================================================== label sampling
def sample_initial_skill(rng: np.random.Generator, pi: np.ndarray) -> int:
    return int(rng.choice(len(pi), p=np.asarray(pi, dtype=float)))


def sample_next_skill(rng: np.random.Generator, transition: np.ndarray,
                      previous: int) -> int:
    row = np.asarray(transition, dtype=float)[int(previous)]
    nxt = int(rng.choice(len(row), p=row))
    if nxt == int(previous):
        raise RuntimeError(f"sampled a self-transition {previous} -> {nxt}; "
                           "P's diagonal must be exactly zero")
    return nxt


# ==================================================================== RNG streams
def component_rng(master_seed: int, split: str, trace_index: int,
                  component: int, *extra: int) -> np.random.Generator:
    """A dedicated deterministic stream per (trace, component)."""
    key = (_SPLIT_CODES[split], int(trace_index), int(component)) + tuple(
        int(v) for v in extra)
    return np.random.default_rng(
        np.random.SeedSequence(entropy=int(master_seed), spawn_key=key))


def block_rng(master_seed: int, split: str, trace_index: int,
              block_index: int) -> np.random.Generator:
    """The block-specific stream: independent of every other block by construction."""
    return component_rng(master_seed, split, trace_index,
                         _COMPONENT_BLOCK_BASE, block_index)


# ===================================================================== trace records
@dataclass(frozen=True)
class MatchedTrace:
    """One generated trace plus its complete hidden truth."""

    trace_index: int
    split: str
    length: int                       # J_n, fixed by design
    widths: tuple                     # sampled S_n as block widths
    boundaries: tuple                 # internal cut positions (hidden truth)
    labels: tuple                     # z_n (hidden truth)
    role_blocks: tuple                # per-block generated role sequences (hidden)
    cpa: tuple                        # observed CPA occurrence sequence x^(n)
    log_seg_prior: float              # log p(S_n | J_n, delta_B), normalized
    log_label_prior: float            # log p(z_n | pi, P)
    block_log_likelihoods: tuple      # generator-accumulated log p_RFS per block

    @property
    def n_segments(self) -> int:
        return len(self.widths)

    def complete_data_log_prob(self) -> float:
        return float(self.log_seg_prior + self.log_label_prior
                     + sum(self.block_log_likelihoods))


@dataclass(frozen=True)
class MatchedCorpus:
    train: tuple
    heldout: tuple
    truth: MatchedTruth
    master_seed: int
    trace_lengths_train: tuple
    trace_lengths_heldout: tuple
    config: dict = field(default_factory=dict)


# ======================================================================= generation
def generate_trace(master_seed: int, split: str, trace_index: int, trace_length: int,
                   truth: MatchedTruth, tables: dict) -> MatchedTrace:
    """Generate one trace in the registered order. ``tables`` must match ``J``."""
    J = int(trace_length)
    params = truth.rfs_parameters()

    # 2. exact segmentation draw
    rng_seg = component_rng(master_seed, split, trace_index, _COMPONENT_SEGMENTATION)
    widths = sample_segmentation_widths(
        rng_seg, J, truth.delta_b, truth.min_width, truth.max_width, tables=tables)
    if sum(widths) != J:
        raise RuntimeError(f"sampled widths {widths} do not sum to J={J}")
    ends = ends_of_widths(widths)
    L = len(widths)

    # 4-5. skill path
    rng_labels = component_rng(master_seed, split, trace_index, _COMPONENT_LABELS)
    labels = [sample_initial_skill(rng_labels, truth.pi)]
    for _ in range(L - 1):
        labels.append(sample_next_skill(rng_labels, truth.transition, labels[-1]))

    # 6. blocks from the production recurrent execution model, one RNG per block
    log_g = tables["log_g"]
    log_seg = ((L - 1) * math.log(truth.delta_b)
               + (J - L) * math.log1p(-truth.delta_b) - float(log_g[J]))
    log_labels = float(np.log(truth.pi[labels[0]]))
    for prev, nxt in zip(labels[:-1], labels[1:]):
        log_labels += float(np.log(truth.transition[prev, nxt]))

    role_blocks, block_log_liks, cpa = [], [], []
    for l, (width, skill) in enumerate(zip(widths, labels)):
        rng_block = block_rng(master_seed, split, trace_index, l)
        roles, steps = sample_recurrent_rfs_sequence(
            rng_block, width, truth.u_by_skill[skill], params, return_trace=True)
        role_blocks.append(tuple(int(v) for v in roles))
        block_log_liks.append(float(sum(
            math.log(step["observed_probability"]) for step in steps)))
        ell = truth.role_maps[skill]
        cpa.extend(int(ell[role]) for role in roles)

    if len(cpa) != J:
        raise RuntimeError(f"generated trace has length {len(cpa)}, expected J={J}")
    return MatchedTrace(
        trace_index=int(trace_index), split=str(split), length=J,
        widths=tuple(int(w) for w in widths), boundaries=tuple(ends[:-1]),
        labels=tuple(int(z) for z in labels), role_blocks=tuple(role_blocks),
        cpa=tuple(cpa), log_seg_prior=float(log_seg),
        log_label_prior=float(log_labels),
        block_log_likelihoods=tuple(block_log_liks))


def generate_corpus(master_seed: int, trace_lengths_train, trace_lengths_heldout,
                    truth: MatchedTruth | None = None) -> MatchedCorpus:
    """Generate a corpus from fixed design trace lengths. Truth is validated first."""
    truth = supplied_truth() if truth is None else truth
    validate_truth(truth)
    lengths_train = tuple(int(v) for v in trace_lengths_train)
    lengths_heldout = tuple(int(v) for v in trace_lengths_heldout)
    tables_by_length = {
        J: width_sampling_tables(J, truth.delta_b, truth.min_width, truth.max_width)
        for J in sorted(set(lengths_train) | set(lengths_heldout))}
    train = tuple(
        generate_trace(master_seed, "train", i, J, truth, tables_by_length[J])
        for i, J in enumerate(lengths_train))
    heldout = tuple(
        generate_trace(master_seed, "heldout", i, J, truth, tables_by_length[J])
        for i, J in enumerate(lengths_heldout))
    config = {
        "generator_version": GENERATOR_VERSION,
        "master_seed": int(master_seed),
        "rng_scheme": "numpy SeedSequence(entropy=master_seed, spawn_key=(split_code, "
                      "trace_index, component[, block_index])); components: "
                      "0=segmentation, 1=labels, 2+block streams",
        "split_codes": dict(_SPLIT_CODES),
        "truth_mode": truth.mode,
        "n_train_traces": len(train), "n_heldout_traces": len(heldout),
        "trace_lengths_train": list(lengths_train),
        "trace_lengths_heldout": list(lengths_heldout),
        "segmentation_prior": "p(S | J, delta_B) = delta_B^(L-1) (1-delta_B)^(J-L) "
                              "/ C_J(delta_B), widths in "
                              f"[{truth.min_width}, {truth.max_width}], exact DP sampler",
        "split_level": "trace",
    }
    return MatchedCorpus(train=train, heldout=heldout, truth=truth,
                         master_seed=int(master_seed),
                         trace_lengths_train=lengths_train,
                         trace_lengths_heldout=lengths_heldout, config=config)


# ============================================== complete-data log-probability parity
def generator_complete_data_log_prob(trace: MatchedTrace) -> float:
    """The generator-side decomposition, accumulated during generation."""
    return trace.complete_data_log_prob()


def inference_complete_data_log_prob(trace: MatchedTrace, truth: MatchedTruth,
                                     scorer, trace_index_in_scorer: int,
                                     log_c_reference: float) -> float:
    """The inference-side route: production boundary prior, production path prior,
    production recurrent block scorer, plus the independently computed normalizer.

    Requires identity role maps, which is what the current registered model uses:
    the production scorer reads observed symbols directly as role indices.
    """
    if not truth.role_maps_are_identity():
        raise AssertionError("the production scorer requires identity role maps")
    with np.errstate(divide="ignore"):
        log_pi = np.log(truth.pi)
        log_transition = np.log(truth.transition)
    total = log_boundary_prior(trace.length, trace.n_segments, truth.delta_b)
    total -= float(log_c_reference)
    total += log_path_prior(trace.labels, log_pi, log_transition)
    start = 0
    for width, skill in zip(trace.widths, trace.labels):
        total += float(scorer.score(trace_index_in_scorer, start, start + width,
                                    int(skill)))
        start += width
    return float(total)


# ================================================================== serialization
def canonical_json(payload) -> str:
    """Deterministic serialization: sorted keys, no whitespace, finite floats only."""
    return json.dumps(payload, sort_keys=True, separators=(",", ":"),
                      allow_nan=False)


def sha256_hex(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def truth_to_jsonable(truth: MatchedTruth) -> dict:
    closures = [truth.precedence(k) for k in range(truth.n_skills)]
    return {
        "mode": truth.mode,
        "n_skills": truth.n_skills, "n_roles": truth.n_roles,
        "latent_dim": truth.latent_dim,
        "u_by_skill": truth.u_by_skill.tolist(),
        "h_by_skill": [c.astype(int).tolist() for c in closures],
        "h_hashes": [sha256_hex(canonical_json(c.astype(int).tolist()))
                     for c in closures],
        "rho": truth.rho,
        "pi": truth.pi.tolist(), "transition": truth.transition.tolist(),
        "scalars": truth.scalars, "epsilon": truth.epsilon,
        "delta_b": truth.delta_b,
        "min_width": truth.min_width, "max_width": truth.max_width,
        "role_maps": [list(row) for row in truth.role_maps],
    }


def truth_from_jsonable(payload: dict) -> MatchedTruth:
    return MatchedTruth(
        u_by_skill=np.array(payload["u_by_skill"], dtype=float),
        pi=np.array(payload["pi"], dtype=float),
        transition=np.array(payload["transition"], dtype=float),
        beta=float(payload["scalars"]["beta"]),
        omega=float(payload["scalars"]["omega"]),
        lambda_rep=float(payload["scalars"]["lambda_rep"]),
        lambda_back=float(payload["scalars"]["lambda_back"]),
        epsilon=float(payload["epsilon"]), delta_b=float(payload["delta_b"]),
        min_width=int(payload["min_width"]), max_width=int(payload["max_width"]),
        role_maps=tuple(tuple(int(v) for v in row) for row in payload["role_maps"]),
        rho=None if payload["rho"] is None else float(payload["rho"]),
        mode=str(payload["mode"]))


def trace_to_jsonable(trace: MatchedTrace) -> dict:
    return {
        "trace_index": trace.trace_index, "split": trace.split,
        "length": trace.length,
        "observed": {"cpa": list(trace.cpa)},
        "hidden_truth": {
            "widths": list(trace.widths), "boundaries": list(trace.boundaries),
            "labels": list(trace.labels),
            "role_blocks": [list(b) for b in trace.role_blocks],
            "log_seg_prior": trace.log_seg_prior,
            "log_label_prior": trace.log_label_prior,
            "block_log_likelihoods": list(trace.block_log_likelihoods),
        },
    }


def trace_from_jsonable(payload: dict) -> MatchedTrace:
    hidden = payload["hidden_truth"]
    return MatchedTrace(
        trace_index=int(payload["trace_index"]), split=str(payload["split"]),
        length=int(payload["length"]),
        widths=tuple(int(v) for v in hidden["widths"]),
        boundaries=tuple(int(v) for v in hidden["boundaries"]),
        labels=tuple(int(v) for v in hidden["labels"]),
        role_blocks=tuple(tuple(int(v) for v in b) for b in hidden["role_blocks"]),
        cpa=tuple(int(v) for v in payload["observed"]["cpa"]),
        log_seg_prior=float(hidden["log_seg_prior"]),
        log_label_prior=float(hidden["log_label_prior"]),
        block_log_likelihoods=tuple(float(v)
                                    for v in hidden["block_log_likelihoods"]))


def corpus_to_jsonable(corpus: MatchedCorpus) -> dict:
    return {
        "config": corpus.config,
        "truth": truth_to_jsonable(corpus.truth),
        "train": [trace_to_jsonable(t) for t in corpus.train],
        "heldout": [trace_to_jsonable(t) for t in corpus.heldout],
    }


def corpus_hash(corpus: MatchedCorpus) -> str:
    """SHA-256 over the canonical serialization. No timestamps, no paths."""
    return sha256_hex(canonical_json(corpus_to_jsonable(corpus)))
