"""Stage 6A — recurrent synthetic corpus, and the exposure audit.

Blocks are generated by exactly the equations the likelihood evaluates, so
generator/likelihood parity is a real check rather than a tautology: the generator
records the probability it actually used, and parity is verified by an *independent
replay* through `recurrent_rfs_log_likelihood`.

The block length ``T`` is supplied externally and never modelled — there is no
``p(T | skill)``, no duration and no stopping rule.

The exposure audit answers a question that must be settled *before* Stage 6B tries to
recover anything: does the corpus contain enough of the right events for the recurrent
parameters to be identifiable at all? A dataset with no upstream repeats cannot inform
``lambda_back``, however long it is.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

from hpop.mcmc_original.latent_poset import precedence_from_u
from hpop.mcmc_original.recurrent_rfs import (
    RecurrentRFSParameters, logit, recurrent_back_costs, recurrent_feasibility,
    recurrent_step_probabilities, recurrent_validity_update,
)

__all__ = [
    "U_TRUE", "U_ANTICHAIN", "TRUE_PARAMETERS", "LATENT_DIM",
    "RecurrentBlock", "RecurrentDataset", "generate_recurrent_dataset",
    "exposure_audit", "assert_stage6_library",
]

LATENT_DIM = 2
U_TRUE = np.array([[4.0, 4.0], [0.0, 5.0], [3.0, 3.0], [2.0, 2.0], [1.0, 1.0]])
U_ANTICHAIN = np.array([[0.0, 4.0], [1.0, 3.0], [2.0, 2.0], [3.0, 1.0], [4.0, 0.0]])

BETA_TRUE, EPSILON_TRUE, KAPPA_TRUE = 1.5, 0.02, 0.85
LAMBDA_REP_TRUE, LAMBDA_BACK_TRUE = 0.8, 0.25
TRUE_PARAMETERS = RecurrentRFSParameters(
    beta=BETA_TRUE, epsilon=EPSILON_TRUE, shared_omega=logit(KAPPA_TRUE),
    lambda_rep=LAMBDA_REP_TRUE, lambda_back=LAMBDA_BACK_TRUE)

TRUE_PAIRS = ((0, 2), (0, 3), (0, 4), (2, 3), (2, 4), (3, 4))


def assert_stage6_library() -> None:
    """Guard the registered poset and the antichain control."""
    p = precedence_from_u(U_TRUE)
    pairs = tuple(sorted((i, j) for i in range(5) for j in range(5) if p[i, j]))
    if pairs != TRUE_PAIRS:
        raise AssertionError(f"U_TRUE closure must be {TRUE_PAIRS}, got {pairs}")
    for j in (0, 2, 3, 4):
        if p[1, j] or p[j, 1]:
            raise AssertionError("role 1 must be incomparable with every other role")
    if precedence_from_u(U_ANTICHAIN).any():
        raise AssertionError("U_ANTICHAIN must induce no ordered pairs")


@dataclass(frozen=True)
class RecurrentBlock:
    roles: tuple[int, ...]
    step_log_probabilities: tuple[float, ...]     # what the generator actually used
    q_before: tuple[tuple[float, ...], ...]       # synthetic truth, not model input
    q_after: tuple[tuple[float, ...], ...]
    back_costs: tuple[tuple[float, ...], ...]
    feasibility: tuple[tuple[float, ...], ...]
    ever_executed_before: tuple[bool, ...]
    split: str

    @property
    def length(self) -> int:
        return len(self.roles)

    @property
    def generator_log_likelihood(self) -> float:
        return float(sum(self.step_log_probabilities))


@dataclass(frozen=True)
class RecurrentDataset:
    train: tuple[RecurrentBlock, ...]
    heldout: tuple[RecurrentBlock, ...]
    u_true: np.ndarray
    parameters: RecurrentRFSParameters
    config: dict = field(default_factory=dict)


def _sample_block(rng, length, u, params, split) -> RecurrentBlock:
    precedence = precedence_from_u(u)
    m = u.shape[0]
    q = np.zeros(m)
    ever = np.zeros(m, dtype=bool)
    roles, logps, qb, qa, backs, feas, everflags = [], [], [], [], [], [], []
    for _ in range(int(length)):
        mixed = recurrent_step_probabilities(u, q, params)
        y = int(rng.choice(m, p=mixed))
        back = recurrent_back_costs(precedence, q, params.shared_omega)
        qb.append(tuple(q.tolist()))
        feas.append(tuple(recurrent_feasibility(precedence, q).tolist()))
        backs.append(tuple(back.tolist()))
        everflags.append(bool(ever[y]))
        roles.append(y)
        logps.append(float(np.log(mixed[y])))
        q = recurrent_validity_update(y, precedence, q, params.shared_omega)
        qa.append(tuple(q.tolist()))
        ever[y] = True
    return RecurrentBlock(tuple(roles), tuple(logps), tuple(qb), tuple(qa),
                          tuple(backs), tuple(feas), tuple(everflags), split)


def generate_recurrent_dataset(mode: str, seed: int, u=None, params=None) -> RecurrentDataset:
    """`smoke` = 50 blocks of T=12; `full` = 500 train + 200 held-out of T=20."""
    assert_stage6_library()
    u = U_TRUE if u is None else u
    params = TRUE_PARAMETERS if params is None else params
    if mode == "smoke":
        n_train, n_heldout, T = 50, 0, 12
    elif mode == "full":
        n_train, n_heldout, T = 500, 200, 20
    else:
        raise ValueError(f"mode must be 'smoke' or 'full', got {mode!r}")

    rng_train = np.random.default_rng(seed)                 # separate recorded streams
    rng_heldout = np.random.default_rng(seed + 10_000)
    train = tuple(_sample_block(rng_train, T, u, params, "train") for _ in range(n_train))
    heldout = tuple(_sample_block(rng_heldout, T, u, params, "heldout")
                    for _ in range(n_heldout))
    config = {"mode": mode, "generator_seed": seed, "seed_train": seed,
              "seed_heldout": seed + 10_000, "T": T, "n_train": n_train,
              "n_heldout": n_heldout, "latent_dim": LATENT_DIM,
              "beta": params.beta, "epsilon": params.epsilon,
              "kappa": params.kappa, "shared_omega": params.shared_omega,
              "lambda_rep": params.lambda_rep, "lambda_back": params.lambda_back,
              "U_true": np.asarray(u).tolist(),
              "likelihood_conditions_on_T": True, "duration_model": None}
    return RecurrentDataset(train, heldout, np.asarray(u), params, config)


def exposure_audit(blocks, u=None) -> dict:
    """Count the events later parameter recovery would need.

    A. valid-role repeat      q_before[y] > 0
    B. leaf repeat            valid, and back_cost[y] ~ 0        -> informs lambda_rep
    C. upstream repeat        valid, and back_cost[y] > 0        -> informs lambda_back
    D. recomputation          executed before, now stale, feasible -> informs omega
    E. gate exposure E_zx     y == z while q_before[x] > 0        -> informs the gate per pair
    """
    u = U_TRUE if u is None else u
    precedence = precedence_from_u(u)
    m = np.asarray(u).shape[0]
    counts = {"valid_repeat": 0, "leaf_repeat": 0, "upstream_repeat": 0, "recomputation": 0}
    by_role = {x: dict(valid_repeat=0, leaf_repeat=0, upstream_repeat=0, recomputation=0)
               for x in range(m)}
    gate = np.zeros((m, m), dtype=int)
    total_steps = 0

    for block in blocks:
        for step, y in enumerate(block.roles):
            total_steps += 1
            q_before = np.array(block.q_before[step])
            back = np.array(block.back_costs[step])
            feas = np.array(block.feasibility[step])
            if q_before[y] > 0.0:
                counts["valid_repeat"] += 1; by_role[y]["valid_repeat"] += 1
                if back[y] <= 1e-12:
                    counts["leaf_repeat"] += 1; by_role[y]["leaf_repeat"] += 1
                else:
                    counts["upstream_repeat"] += 1; by_role[y]["upstream_repeat"] += 1
            if block.ever_executed_before[step] and q_before[y] < 1 - 1e-8 and feas[y] > 0.0:
                counts["recomputation"] += 1; by_role[y]["recomputation"] += 1
            for x in range(m):
                if precedence[y, x] and q_before[x] > 1e-8:
                    gate[y, x] += 1

    return {"total_steps": total_steps, "n_blocks": len(blocks), **counts,
            "by_role": by_role, "gate_exposure": gate.tolist(),
            "gate_exposure_true_pairs": {f"{z}->{x}": int(gate[z, x]) for z, x in TRUE_PAIRS}}
