"""Per-skill role maps over a CPA vocabulary larger than any one skill's role inventory.

The registered model reads an observed trace symbol **directly** as a row index into
`u_by_skill[k]`, which forces the vocabulary size `A` to equal the per-skill role count
`m`. `matched_synthetic_generator` says so in as many words -- it raises
`"the production scorer requires identity role maps"`. Every experiment so far therefore
ran at `A = m = 5`, with all skills sharing one five-symbol alphabet and differing only in
their partial order over it.

That is fine at `K = 3` and degenerate at `K = 30`: thirty skills crowded onto five shared
symbols are nearly indistinguishable, and a recovery ladder built on them would measure the
crowding rather than the effect of library size.

This module supplies the missing layer. A skill `k` owns an **injective** map

    ell_k : {0, ..., m-1}  ->  {0, ..., A-1}

so role `r` of skill `k` emits CPA `ell_k(r)`. Its support is the image of that map. A
block whose observed CPAs all lie in skill `k`'s support is translated back to role indices
and scored by the ordinary recurrent likelihood; a block containing any CPA outside the
support **cannot have been generated by that skill** and scores `-inf`.

## Why the likelihood needs no correction term

`ell_k` is injective, so an observed CPA determines its role uniquely. The emission
distribution is over the `m` roles and the map is deterministic, so the density over CPAs
is the density over roles -- no Jacobian, no renormalisation. The `epsilon / m` uniform
component stays over `m`, not over `A`, because it is a slip among the roles the skill has,
not among every action in the world.

Nothing here edits `hpop.mcmc_original`. This is a new layer that translates before the
sealed arithmetic runs.
"""

from __future__ import annotations

import hashlib

import numpy as np

__all__ = ["RoleMaps", "sample_role_maps"]

NOT_IN_SUPPORT = -1


class RoleMaps:
    """`K` injective maps from a skill's role index to a global CPA id.

    `forward[k, r]` is the CPA that role `r` of skill `k` emits.
    `inverse[k, c]` is the role index of CPA `c` under skill `k`, or `-1` if `c` is not in
    that skill's support.
    """

    __slots__ = ("forward", "inverse", "n_skills", "n_roles", "n_cpa")

    def __init__(self, forward, n_cpa: int):
        forward = np.asarray(forward, dtype=np.int64)
        if forward.ndim != 2:
            raise ValueError(f"role maps must be (K, m), got {forward.shape}")
        self.n_skills, self.n_roles = (int(v) for v in forward.shape)
        self.n_cpa = int(n_cpa)
        if self.n_roles > self.n_cpa:
            raise ValueError(
                f"a skill cannot have more roles ({self.n_roles}) than the vocabulary "
                f"has symbols ({self.n_cpa})")
        if forward.min() < 0 or forward.max() >= self.n_cpa:
            raise ValueError("a role map points outside the CPA vocabulary")
        for k in range(self.n_skills):
            if len(np.unique(forward[k])) != self.n_roles:
                raise ValueError(f"role map for skill {k} is not injective")
        self.forward = forward
        self.inverse = np.full((self.n_skills, self.n_cpa), NOT_IN_SUPPORT,
                               dtype=np.int64)
        rows = np.repeat(np.arange(self.n_skills), self.n_roles)
        self.inverse[rows, forward.ravel()] = np.tile(np.arange(self.n_roles),
                                                      self.n_skills)

    # ------------------------------------------------------------------ translation
    def to_roles(self, trace) -> np.ndarray:
        """`(K, J)` role indices for one CPA trace, `-1` where a CPA is out of support."""
        return self.inverse[:, np.asarray(trace, dtype=np.int64)]

    def supports(self) -> list:
        return [np.sort(self.forward[k]) for k in range(self.n_skills)]

    def is_identity(self) -> bool:
        """True exactly when this reduces to the registered `A = m` model."""
        return (self.n_roles == self.n_cpa and
                all(np.array_equal(self.forward[k], np.arange(self.n_roles))
                    for k in range(self.n_skills)))

    # ------------------------------------------------------------------ bookkeeping
    def overlap_matrix(self) -> np.ndarray:
        """`O[j, k]` = how many CPAs skills `j` and `k` share. Recorded, never tuned on."""
        member = np.zeros((self.n_skills, self.n_cpa), dtype=bool)
        for k in range(self.n_skills):
            member[k, self.forward[k]] = True
        return (member.astype(np.int64) @ member.T.astype(np.int64))

    def digest(self) -> str:
        return hashlib.sha256(
            np.ascontiguousarray(self.forward).tobytes()
            + str(self.n_cpa).encode()).hexdigest()[:16]

    def as_dict(self) -> dict:
        overlap = self.overlap_matrix()
        off = overlap[~np.eye(self.n_skills, dtype=bool)] if self.n_skills > 1 \
            else np.array([0])
        return {
            "n_skills": self.n_skills, "n_roles": self.n_roles, "n_cpa": self.n_cpa,
            "forward": self.forward.tolist(),
            "supports": [s.tolist() for s in self.supports()],
            "is_identity": bool(self.is_identity()),
            "pairwise_overlap_min": int(off.min()), "pairwise_overlap_max": int(off.max()),
            "pairwise_overlap_mean": float(off.mean()),
            "digest": self.digest(),
        }

    @classmethod
    def identity(cls, n_skills: int, n_roles: int) -> "RoleMaps":
        """The registered `A = m` model, as a role map. Used to pin the two together."""
        return cls(np.tile(np.arange(int(n_roles)), (int(n_skills), 1)), int(n_roles))


def sample_role_maps(n_skills: int, n_roles: int, n_cpa: int, seed: int,
                     max_attempts: int = 1000) -> RoleMaps:
    """Deterministic injective maps with pairwise-distinct supports.

    Distinct supports are required by the ladder's admissibility conditions -- two skills
    with the same CPA support would be separable only by their internal order, which is
    the degeneracy this layer exists to remove. Sampling is rejection-based on that one
    condition and nothing else; no criterion here looks at data, likelihood or recovery.
    """
    n_skills, n_roles, n_cpa = int(n_skills), int(n_roles), int(n_cpa)
    rng = np.random.default_rng(int(seed))
    for _ in range(int(max_attempts)):
        forward = np.stack([rng.choice(n_cpa, size=n_roles, replace=False)
                            for _ in range(n_skills)])
        keys = {tuple(sorted(row)) for row in forward.tolist()}
        if len(keys) == n_skills:
            return RoleMaps(forward, n_cpa)
    raise RuntimeError(
        f"no {n_skills} pairwise-distinct supports of size {n_roles} drawn from "
        f"{n_cpa} CPAs in {max_attempts} attempts")
