"""VENDORED verbatim copies of the registered diagnostic/probe definitions.

Generated by scripts/make_midrun_vendor.py.  This module exists so the read-only
mid-run analysis never imports a source file that the live FULL-LATENT workers use.
Every function below is a byte-verbatim copy of its registered definition; the source
file SHA-256 digests are recorded in SOURCE_DIGESTS and re-verified at import.
"""
from __future__ import annotations
import hashlib, math
import numpy as np
from scipy import stats


# ---- verbatim from src/hpop/mcmc_original/stage6b_mcmc_diagnostics.py ----

def autocovariance(chains: np.ndarray) -> np.ndarray:
    """Biased autocovariance (denominator ``N``) per chain, by FFT. Shape ``(C, N)``."""
    chains = np.atleast_2d(np.asarray(chains, dtype=float))
    n = chains.shape[-1]
    centred = chains - chains.mean(axis=-1, keepdims=True)
    size = int(2 ** math.ceil(math.log2(2 * n)))
    spectrum = np.fft.rfft(centred, n=size, axis=-1)
    spectrum *= np.conjugate(spectrum)
    acov = np.fft.irfft(spectrum, n=size, axis=-1)[..., :n]
    return acov / n

def effective_sample_size_core(chains: np.ndarray) -> float:
    """Geyer initial monotone positive sequence ESS across chains (Vehtari et al. 2021)."""
    chains = np.atleast_2d(np.asarray(chains, dtype=float))
    n_chain, n_draw = chains.shape
    if n_draw < 4:
        return float("nan")
    if np.allclose(chains, chains.flat[0]):
        return float("nan")

    acov = autocovariance(chains)
    chain_mean = chains.mean(axis=-1)
    mean_var = float(np.mean(acov[:, 0])) * n_draw / (n_draw - 1.0)
    var_plus = mean_var * (n_draw - 1.0) / n_draw
    if n_chain > 1:
        var_plus += float(np.var(chain_mean, ddof=1))
    if var_plus <= 0:
        return float("nan")

    rho = np.zeros(n_draw)
    rho[0] = 1.0
    rho_even = 1.0
    rho_odd = 1.0 - (mean_var - float(np.mean(acov[:, 1]))) / var_plus
    rho[1] = rho_odd

    t = 1
    while t < (n_draw - 3) and (rho_even + rho_odd) > 0.0:
        rho_even = 1.0 - (mean_var - float(np.mean(acov[:, t + 1]))) / var_plus
        rho_odd = 1.0 - (mean_var - float(np.mean(acov[:, t + 2]))) / var_plus
        if (rho_even + rho_odd) >= 0.0:
            rho[t + 1] = rho_even
            rho[t + 2] = rho_odd
        t += 2

    max_t = t - 2
    if rho_even > 0.0:
        rho[max_t + 1] = rho_even

    # enforce the initial monotone sequence on consecutive pair sums
    k = 1
    while k <= max_t - 2:
        pair = rho[k + 1] + rho[k + 2]
        if pair > (rho[k - 1] + rho[k]):
            rho[k + 1] = (rho[k - 1] + rho[k]) / 2.0
            rho[k + 2] = rho[k + 1]
        k += 2

    total = n_chain * n_draw
    tau = -1.0 + 2.0 * float(np.sum(rho[: max_t + 1])) + float(np.sum(rho[max_t + 1: max_t + 2]))
    tau = max(tau, 1.0 / math.log10(total))
    return float(total / tau)

def rank_normalize(values: np.ndarray) -> np.ndarray:
    """Blom rank-normalisation: ``Phi^-1((r - 3/8) / (S - 1/4))`` over all draws jointly."""
    values = np.asarray(values, dtype=float)
    ranks = stats.rankdata(values, method="average").reshape(values.shape)
    size = values.size
    return stats.norm.ppf((ranks - 0.375) / (size - 0.25))

def split_chains(chains: np.ndarray) -> np.ndarray:
    """``(C, N)`` -> ``(2C, N // 2)``, discarding one draw when ``N`` is odd."""
    chains = np.atleast_2d(np.asarray(chains, dtype=float))
    half = chains.shape[-1] // 2
    return np.vstack([chains[:, :half], chains[:, -half:]])

def _classic_rhat(chains: np.ndarray) -> float:
    chains = np.atleast_2d(np.asarray(chains, dtype=float))
    n_chain, n_draw = chains.shape
    if n_chain < 2 or n_draw < 2:
        return float("nan")
    within = float(chains.var(axis=-1, ddof=1).mean())
    between = float(chains.mean(axis=-1).var(ddof=1))
    if within == 0.0:
        return float("nan") if between > 0 else 1.0
    var_hat = (n_draw - 1) / n_draw * within + between
    return float(math.sqrt(var_hat / within))

def _fold(chains: np.ndarray) -> np.ndarray:
    chains = np.asarray(chains, dtype=float)
    return np.abs(chains - np.median(chains))

def rank_normalized_split_rhat(chains: np.ndarray) -> dict:
    """Bulk and folded-tail split R-hat, and the reported maximum."""
    chains = np.atleast_2d(np.asarray(chains, dtype=float))
    bulk = _classic_rhat(rank_normalize(split_chains(chains)))
    tail = _classic_rhat(rank_normalize(split_chains(_fold(chains))))
    return {"rhat_bulk": bulk, "rhat_tail": tail, "rhat": float(max(bulk, tail))}

def bulk_ess(chains: np.ndarray) -> float:
    return effective_sample_size_core(rank_normalize(split_chains(chains)))

def tail_ess(chains: np.ndarray, prob: tuple[float, float] = (0.05, 0.95)) -> float:
    chains = np.atleast_2d(np.asarray(chains, dtype=float))
    low, high = np.quantile(chains, prob)
    below_low = (chains <= low).astype(float)
    below_high = (chains <= high).astype(float)
    return float(min(
        effective_sample_size_core(rank_normalize(split_chains(below_low))),
        effective_sample_size_core(rank_normalize(split_chains(below_high)))))

# ---- verbatim from src/hpop/mcmc_original/matched_full_latent.py ----

def _stable_rank(corpus_hash: str, kind: str, *parts: int) -> bytes:
    text = "|".join((str(corpus_hash), str(kind), *(str(int(v)) for v in parts)))
    return hashlib.sha256(text.encode("utf-8")).digest()

def select_truth_free_probes(traces, corpus_hash: str, boundary_count: int = 32,
                             coskill_count: int = 64,
                             recovery_coskill_count: int = 256) -> dict:
    """Deterministically select finite truth-free diagnostic/recovery probes."""
    boundary_candidates = [(n, position)
                           for n, trace in enumerate(traces)
                           for position in range(len(trace) - 1)]
    boundary_candidates.sort(key=lambda p: _stable_rank(corpus_hash, "boundary", *p))
    pair_candidates = [(n, left, right)
                       for n, trace in enumerate(traces)
                       for left in range(len(trace))
                       for right in range(left + 1, len(trace))]
    pair_candidates.sort(key=lambda p: _stable_rank(corpus_hash, "coskill", *p))
    recovery_count = min(int(recovery_coskill_count), len(pair_candidates))
    return {
        "boundary": tuple(boundary_candidates[:min(int(boundary_count),
                                                    len(boundary_candidates))]),
        "coskill": tuple(pair_candidates[:min(int(coskill_count),
                                                len(pair_candidates))]),
        "recovery_coskill": tuple(pair_candidates[:recovery_count]),
    }

SOURCE_DIGESTS = {'src/hpop/mcmc_original/stage6b_mcmc_diagnostics.py': '2eb8de60118eee3316e0ab5493de88c235976e20b1be84de93078191a999f38b', 'src/hpop/mcmc_original/matched_full_latent.py': '91c108c8cb4d3903dae04b70fc849b90496ca052b45572c28990faad8c36d038'}

def verify_sources(root="."):
    import pathlib as _p, hashlib as _h
    for rel, want in SOURCE_DIGESTS.items():
        got = _h.sha256((_p.Path(root)/rel).read_bytes()).hexdigest()
        if got != want:
            raise AssertionError(f"vendored source drifted: {rel}")
    return True
